services:
  - type: web
    name: cyberchall-app
	runtime: java
    plan: free
    buildCommand: ./mvnw clean install || mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17